---
apiVersion: v1
kind: Service
metadata:
  name: nginxpm
  namespace: {{ .Values.namespace.name }}
  labels:
    app: nginxpm
spec:
  type: {{ .Values.nginxpm.service.type }}
  selector:
    app: nginxpm
  ports:
    - name: http
      port: {{ .Values.nginxpm.service.http.port }}
      targetPort: http
      {{- if eq .Values.nginxpm.service.type "NodePort" }}
      nodePort: {{ .Values.nginxpm.service.http.nodePort }}
      {{- end }}
      protocol: TCP
    - name: https
      port: {{ .Values.nginxpm.service.https.port }}
      targetPort: https
      {{- if eq .Values.nginxpm.service.type "NodePort" }}
      nodePort: {{ .Values.nginxpm.service.https.nodePort }}
      {{- end }}
      protocol: TCP
    - name: admin-ui
      port: {{ .Values.nginxpm.service.admin.port }}
      targetPort: admin-ui
      {{- if eq .Values.nginxpm.service.type "NodePort" }}
      nodePort: {{ .Values.nginxpm.service.admin.nodePort }}
      {{- end }}
      protocol: TCP
